sudo: false
language: rust
cache:
  cargo: true
  directories:
   - $HOME/deps

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4fd67aa92c02652d2c36
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always    # options: [always|never|change] default: always

matrix:
  include:
    - os: linux
      rust: nightly
      compiler: gcc
    - os: osx
      rust: nightly
      osx_image: xcode9
      compiler: clang

script:
  - cargo fmt -- --write-mode=diff
  - cargo test --verbose
  - cargo build --release --verbose --all